### ISSUE TITLE
Push notification not working After parse server migrate, in ios.

### ISSUE THREAD

**Issue by AbhishekSharma0981** [parse-community/Parse-SDK-iOS-OSX#1010]
I am using latest version of parse Sdk in Ios AND now push notification is not woking. I have tried all the different approaches to fix this push notification issue in ios swift but the issue is still exist.

**Comment by pjchavarria** [comment]
Why don't you give us more details so we can help you fix the problem? like server and client configuration

**Comment by anibalrosado** [comment]
Did you ever find out your issue here? We seem to be experiencing the same immediately following the migration of our app from parse.com to our own internal parse servers. Other apps we migrated last week are working fine but now this very important app is not receiving pushes. Please advise or help. Thanks!
