### ISSUE TITLE
What happened to the parse iOS quickstart guide?

### ISSUE THREAD

**Issue by jefferythewind** [parse-community/Parse-SDK-iOS-OSX#1123]
I am setting up an iOS projects, and I wanted a list of all dependent frameworks required by the parese ios SDK, and i have found a lot of links from Parse's own documents and also stack overflow to this link: http://parseplatform.org/#parse_data/mobile/ios/native/new

But that doesn't seem to exist anymore and I just get the main page.

From the parse docs ( http://parseplatform.org/docs/ios/guide/ ) its the link that says, "head over to the quickstart guide", which is the link that i posted above.

**Comment by jefferythewind** [comment]
Seems like I could build successfully and `initialize` pares  by adding only Systemconfiguration.framework and libsqlite.tbd.  Which seems different from the long list of frameworks I see in the stack overflow answers: http://stackoverflow.com/questions/18319885/link-errors-with-parse-framework-ios/18319944#18319944

I am assuming I will run into more errors as I need to use more of the different features on the framework.

**Comment by PunkStarStudios** [comment]
All the guides just disappeared :(

Would be great if they were downloadable for offline viewing... like a PDF.

**Comment by montymxb** [comment]
@PunkStarStudios  Looks like all the docs have been moved. You can still get the guides at [docs.parseplatform.org](http://docs.parseplatform.org), albeit it looks rather ugly at the moment due to some missing assets. I'm not aware of much else at the moment however, other than migration issues it would seem.

The source for the docs is on github [here](https://github.com/parse-community/docs). You can check those out and view them, or save them offline while things are being sorted out.
