### ISSUE TITLE
Crash on app startup with Parse SDK 1.17.1

### ISSUE THREAD

**Issue by cubycode** [parse-community/Parse-SDK-iOS-OSX#1287]
I've just extracted all Parse frameworks with Carthage and dragged them in my own Xcode 9 project. When I run it, I get this error:
```
dyld: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: /var/containers/Bundle/Application/E15FC19F-9920-486A-B769-4E52A3757A46/ParseDemo.app/ParseDemo
  Reason: image not found
(lldb) 
```
The **FBSDKCoreKit.framework** is successfully linked in the Binaries of my project. This issue never happened with older Parse SDK.

I've tried removing the Facebook SDKs, but I get a similar crash on startup, with no console messages but this thread:

```
dyld`__abort_with_payload:
    0x10338af40 <+0>:  mov    x16, #0x209
    0x10338af44 <+4>:  svc    #0x80
->  0x10338af48 <+8>:  b.lo   0x10338af60               ; <+32>
    0x10338af4c <+12>: stp    x29, x30, [sp, #-0x10]!
    0x10338af50 <+16>: mov    x29, sp
    0x10338af54 <+20>: bl     0x10338a5d8               ; cerror_nocancel
    0x10338af58 <+24>: mov    sp, x29
    0x10338af5c <+28>: ldp    x29, x30, [sp], #0x10
    0x10338af60 <+32>: ret  
```  
Am I missing something, maybe in my LInked frameworks section?

![frameworks](https://user-images.githubusercontent.com/14360232/37955044-b9071bac-31a7-11e8-957d-37f6c15db321.png)

**Comment by tealshift** [comment]
Hmmm I'm not versed in Carthage and what you did to obtain the individual frameworks, but I have CocoaPods a problem that could be related.
When my podfile has:
```
target 'MyApp' do
  pod 'Parse/UI'
  pod 'Parse/FacebookUtils'
end

target 'iMessage App' do
    pod 'Parse/Core'
end
```
the facebook classes aren't properly linked since I get a `dyld: Symbol not found: _OBJC_CLASS_$_PFFacebookUtils` at runtime (simulator).

But adding `Parse/FacebookUtils` to the iMessage extension makes it work!
Unfortunately for me, the facebook utils contains references to UIApplication which is not allowed in extensions.
I'm sweating over this. I can't figure a way around it.
