### ISSUE TITLE
PFQuery issue with NSpredicate 

### ISSUE THREAD

**Issue by CurItUK** [parse-community/Parse-SDK-iOS-OSX#1330]
Hi,  
I am building a chat application using Livequery, the chat works well with 
```
      let predicate = NSPredicate(format:"itemID = '\(itemId1)' OR itemID = '\(itemId2)'")
        query = Message.query(with: predicate)?.order(byAscending: "createdAt")
       let query = PFQuery(className: MY_CLASS_NAME, predicate: predicate)
```

this works well if I don't  use live queries and pull with time interval.
Livequery also works if I don't add predicate. 
Below is the error I get
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (PFQuery)' `

any ideas ?
Thanks

**Comment by flovilmart** [comment]
Closing at the same issue is tracked there: https://github.com/parse-community/ParseLiveQuery-iOS-OSX/issues/156

Feel free to open a PR. 

As a work around, instead of making an `$or` query you can use the containedIn:
```
Message.query()?.whereKey("itemId", containedIn: [itemId1, itemId2])
```

This is more efficient also server side as it will be resolved in a single query.
