### ISSUE TITLE
"Carthage update" failing with "file not found"

### ISSUE THREAD

**Issue by mrmarcsmith** [parse-community/Parse-SDK-iOS-OSX#1431]
The Docs say that we should be able to use Carthage to import the Parse SDK into Xcode projects.

### What I expect to happen
`Carthage update` succeeds

### What actually happens
`carthage update` fails

### Environment:
Cartfile: github "parse-community/Parse-SDK-iOS-OSX"
Xcode: 10.2.1
Carthage: 0.33.0

### Attempt 1:
1. delete the Carthage folder and Cartfile.resolved
2. run `carthage upgrade`

it fails with
``` 
fatal error: 'FBSDKTVOSKit/FBSDKDeviceLoginViewController.h' file not found
#import <FBSDKTVOSKit/FBSDKDeviceLoginViewController.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
### Attempt 2:
1. delete the Carthage folder and Cartfile.resolved
2. run `carthage update --no-build`
3. run `carthage build --platform iOS`

```
fatal error: 'FBSDKLoginKit/FBSDKLoginManager.h' file not found
#import <FBSDKLoginKit/FBSDKLoginManager.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mrmarcsmith** [comment]
@mman I saw in #1396 that is was working for you. is that still the case?

**Comment by mman** [comment]
@mrmarcsmith I managed to ``carthage update`` at the time when I posted the update, that is with all component versions as of Mar 27. Since it was before freezing the release for me, I did not attempt to ``carthage update`` again for another month, but when I tried last during end of Jun it was broken.  I do not have a time to test right now and will get back to it only around end of Aug.

**Comment by mysolution** [comment]
I have same issue with FBSDKLoginManager.h

Xcode 10.3
Carthage 0.33.0
