### ISSUE TITLE
Support for "iPad apps for Mac" aka Marzipan/Catalyst

### ISSUE THREAD

**Issue by bbrv2018** [parse-community/Parse-SDK-iOS-OSX#1432]
Dear All,

Is it possible to get clarification on running Parse with Catalyst/Marzipan/"iPad apps on the Mac"? 

Has anyone done it? 
Is it supported? or planned to be? 

Cheers :)

**Comment by TomWFox** [comment]
In terms of support / plans - if work is needed to make this SDK compatible then we would absolutely welcome contribution to do so but we don’t have enough person power to be thinking about new features so it’s really up to individuals to get involved 🙂

**Comment by bmueller** [comment]
FYI I was able to get this up and running pretty quickly by just sticking the Parse Xcode project into my app. The only line of code that needed to be modified was NSURLCache's initWithMemoryCapacity:diskCapacity:diskPath: because it was deprecated and not included in UIKitForMac, just have to change diskPath to directoryURL.

**Comment by MaxMaxP** [comment]
On my project doesn't compile and return back an error that cannot find UIWebView

**Comment by bmueller** [comment]
You can just comment out those lines if you're not going to use that feature in Parse (which I never would), or just switch from UIWebView over to WKWebView, which is supported on Catalyst.
