### ISSUE TITLE
iOS 13 and Xcode 11 build update

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/Parse-SDK-iOS-OSX#1446]
Apple is officially allowing submission of iOS and iPad OS 13 applications. I wanted to start a issue to start getting the ball rolling as this is going to require:

- iPad OS target be added
- Test/Deploy XCode version be updated for CircleCI/Travis
- New Build Target added to test files.

Being that the official iOS/ iPad OS release date coming on September 30th we might want to start moving.

**Comment by noobs2ninjas** [comment]
Quick update. We are using the xcode11 branch for this update which I assume will be 1.18. I have updated build files on this branch to get CircleCI and Travis building on Xcode 11. I'll start working on updating the rake files but I'd appreciate some help adding the iPad OS target if anyone would like to help.

**Comment by noobs2ninjas** [comment]
So I guess well add iPad OS at a later date and just add the Xcode 11 build update to 1.17.3.

**Comment by noobs2ninjas** [comment]
Ok so I finally figured out where these stupid errors where coming from when Travis was trying to build and deploy. Turns out a non-documented repo controls the Vendor folder/build config. Which means we have to update all travis device and OS versions there. Took me so long to figure out why nothing responded and even longer as to why changing those files locally refused to commit. So, whenever my merge goes through on the xcodebuildtools repo I think all we have to do is trigger Travis to rebuild and it should do a submodule update and FINALLY build and deploy. I'm getting a weird sense of deja vu here. This should be it this time though.

@drdaz It being as it was this much work to get everything all updated to finally push the 1.17.3 release do you want to just add this to those release notes and call it a day? We can make adding the iPad OS target 1.18.0 and a few other things like perhapse Apple Sign In.

**Comment by noobs2ninjas** [comment]
So we have a new error on the Travis build after retriggering now that the Xcodebuildtools repo has been updated. 


The following build commands failed:
1743	AnalyzeShallow Parse/PFQuery.m normal arm64
1744(1 failure)
1745Failed to build framework for iphoneos.

Also said something about unexpected end of file

**Comment by noobs2ninjas** [comment]
Never mind. Triggered rebuild and that went away and now we have the same error. My guess is we have to pull the Xcodebuild tools version ourselves or something,

**Comment by drdaz** [comment]
@noobs2ninjas You do have to bump the submodule version in the SDK for the changes to affect the SDK. It's in Vendor/.

I don't know if you caught it btw, but I manually updated the current version in CocoaPods. So no rush to get the release mechanics working.

**Comment by noobs2ninjas** [comment]
@drdaz the reason I have not manually updated the cocoapods version is because I wanted the travis deployment build to trigger. I can update the submodule version but now there is no way to trigger the build to test if its fixed.

**Comment by noobs2ninjas** [comment]
So I guess this will just stay open till the next release whenever that may be.

**Comment by noobs2ninjas** [comment]
If someone else wants to update the submodule they can. I'm going back to ParseLiveQuery

**Comment by drdaz** [comment]
Okay.

`@drdaz the reason I have not manually updated the cocoapods version is because I wanted the travis deployment build to trigger. I can update the submodule version but now there is no way to trigger the build to test if its fixed.`

The deployment build runs every night automatically. I get an email about it every day. Here's the run from last night: https://circleci.com/gh/parse-community/Parse-SDK-iOS-OSX/3412

I'm also fairly sure that the script that runs the Cocoapods version update is only triggered by a new tag being pushed. I've only seen that report once, and it came after I tagged the release.

```
So I guess this will just stay open till the next release whenever that may be.
If someone else wants to update the submodule they can. I'm going back to ParseLiveQuery
```

While I understand it's frustrating that I manually updated the pod, hopefully you understand why I did it? I didn't do it lightly; I'd much prefer it was mechanically released. But Cocoapods had been broken for months, and that's a real problem that real users were running into. And I don't agree that moving master to an unreleased Xcode 11 environment (without review, and despite developer objection) was the right way to fix that problem.

Don't get me wrong; I think it's an epic piece of work you've done here, and it's a *major* asset that we have those changes ready. I'm *really* happy to see you getting to grips with the inner workings of these libs. It's hard when we don't have the previous maintainers to guide us.

**Comment by noobs2ninjas** [comment]
The issue we where facing had NOTHING to do with CircleCI because CircleCI doesn’t use cocoapods or the xcodetoolchain when it builds. No, the ONLY way to test if our issue is fixed is during the Travis release build. Now that the release has been updated the Travis build will never initialize. It only runs when there is a new release that hasn’t been pushed.

As to everything else you said. I already told you. Per Apple Xcode 11 is released. At the time it just hadn’t been reflected on the App Store. Now it has. You can download it yourself off the App Store right now. 

Regardless, our problems had NOTHING to do with Travis or Circle building for Xcode 11 at any point during this process. Our issues came from finding compatible versions of gems and updating our scripts to the reflect changes Travis made In their own system when they updated to Xcode 11. So, while I appreciate your willingness to engage with me during this process, you blaming everything on a “unreleased” version of Xcode shows an absolute lack of understanding on the issues we faced during this process. Had you understood the issue you wouldn’t have manually pushed the release because you would have know that a new and unpushed release tag is the only way to trigger the build we where having problems with

**Comment by noobs2ninjas** [comment]
The good news about all this is that when it's finally updated and working we wont have to do it again for a VERY VERY long time. I actually think all it may take is updating the submodule versions and thats it. At the point when we hit the issue with the xcodetoolchain the project was already building. It just couldnt launch a simulator.

**Comment by drdaz** [comment]
> The issue we where facing had NOTHING to do with CircleCI because CircleCI doesn’t use cocoapods or the xcodetoolchain when it builds. The ONLY way to test if our issue is fixed is during the Travis release build. Now that the release has been updated the Travis build will never initialize. It only runs when there is a new release that hasn’t been pushed.

Right. But the release tag had been pushed the day before you started this PR, and the Travis build failed. Here's the build: https://travis-ci.org/parse-community/Parse-SDK-iOS-OSX/builds/584608026

The net result of the failed Travis build was, as far as I could see when I checked, that Cocoapods was stuck on 1.17.2. 

> Per Apple, Xcode 11 is released. At the time it just hadn’t been reflected on the App Store. Now it has. You can download it yourself off the App Store right now. Regardless, our problems never had anything to do with the Xcode 11 build itself at any point during this process. 

I don't know how long you've been doing this, but I've been doing it long enough to have real PTSD from jumping into pre-release software 🥴. It's great to do it at home or on it's own branch, but never for anything of this scale. At least not without prior consensus. I'd have been corrected for something like that anywhere I'd worked. And for good reason - there can be no expectation of quality in pre-release software.

> Instead it came from gem compatibility and updating scripts to reflect changes made to Travis' internal system. All of which would have occurred to some extent to even updating the build to 10.2.

And it's absolutely glorious that you fixed this! These fixes I wanted in mainline, as long as they could build 10.x 😊. I contested the Xcode version number only.

> To me the excuse that cocoapods has been broken for months as a reason to not fix it and instead manually push out the build makes no sense to me. What’s going to happen next time we have a release? At some point it has to either get fixed or we might as well just get rid of it. I guess thats just a difference in approach though and can respect the urgency to push out a new version. I'm mainly frustrated because I lost my release flag.

It *is* frustrating that we can't see the Travis build run. But I'd look at what the Travis release does, and see if we don't have that covered by commit-triggered or nightly tests already. I think we do, which is a good thing. If we don't, we should get that; the more we can run the release logic before release, the better.

Really, you should be running these tasks locally as far as you can before committing your changes.

> What makes this issue so hard is that you cant test it in a merge. 

Why can't we do that? If we need that to change, surely we can make that happen?

> It only uses the current code on master when it builds. You only can do it when release is marked. 

I'm not sure I understand. Can you tell me which things that aren't being otherwise tested, that you'd like to see tested? Then we can make them happen.

Every night, CircleCI tasks run. They test deployment, Cocoapods and Carthage builds. The Travis release task seems to run a deployment task and a Cocoapods task. I'm assuming (dangerous, I know), that these are the same deployment and Cocoapods tasks, precisely so that the release mechanics are regularly tested. I would currently expect the release task to fail with the same error that last night's deployment task failed with, wouldn't you? 🙂

> Also, you where right, I was frustrated. I'm very new to this. I posted build issues and waited for someone to step in. Nothing. I figured, at some point someone was going to have to learn to do it and maintain our CI/CD for iOS/OSX. Figured it might as well be me. Beats waiting around for someone else to do it.

I totally understand that. And the work is greatly appreciated; I really like the energy. But there's a reason for the review system, and I do think we should follow it.

**Comment by noobs2ninjas** [comment]
So I think I should probably cover what the actual issue is as that seems to be our disconnect. I still could really use any input to find another way to test and fix our issues. First let me touch on two things you mentioned.

> I don't know how long you've been doing this, but I've been doing it long enough to have real PTSD from jumping into pre-release software

Im super confused why you keep using words like pre-released in association to what I was doing. Xcode 11 is released. It's not in beta 4 or even on golden master. Its 100% released. On the macOS app store being downloaded by millions of developers as we speak. For sure its NEW software but it's released.
https://apps.apple.com/us/app/xcode/id497799835?mt=12

I do get your concern and 100% appreciate it. The only reason I insisted is because I didn't want to be doing this again 2 weeks later. 

> But there's a reason for the review system, and I do think we should follow it.

100% honesty I had never seen the squash and merge button without someone approving the pull request before. I still am not aware of what permissions I have been given. So, when I saw the button I assumed someone had reviewed it. I 100% agree with you and promise I will always wait for review going forward.

Ok, so heres the scoop on whats going on with the travis build. 

1) Travis' configuration is as release only script.  

```
jobs:
  include:
    - stage: release
      env: Deployment
```

It does not build nightly. It does not build with each pull request. It doesn't even normally build after a merge/commit. Travis only fires up whenever there is a merge or commit with an outstanding release version/tag that has not yet been successfully deployed. 

**Update:** I'm starting to rethink this. I guess I need to look up the difference between "Deployment" and "Release" stages in this environment. I realized the travis build has been building with every merge/commit to the main branch. At the same time it hasnt passed for quite a long time and may still have internal flags making it think its still trying to deploy a new release. 

2) Because it's a release build it will ONLY pull and build code on the master branch. This includes configuration files, Gemfile, submodules, etc..

This is one of the main reasons it's such a pain to try and fix. If you have to fix the build itself the changes have to already be on the main branch before you even know if it will work. 

This one I know i'm right about. The configuration changes in my pull request only was included in the build after it was merged.

3) Travis has its own internal build environments that determine everything from what version of ruby and bundler are being used, to even what version of OSX is running and what simulators are available.

This is what makes it pretty much impossible to test locally. During this process I ran into build errors that dealt with bundler. The bundler issue led to issues with which version of ruby being used. After that I had issues with which simulators and iOS versions where installed. You have to remember. This isnt just a matter of running a simple script for cocoapod execute a build for your podspec. Everything has to line up or you get "build" errors. This is also why I found different environment issues on both Circle and Travis.

**Comment by drdaz** [comment]
> Im super confused why you keep using words like pre-released in association to what I was doing. Xcode 11 is released. It's not in beta 4 or even on golden master. Its 100% released.

Today, it's released. When you were making these changes and merging them, it wasn't released (GM seed 2 was the current state), and there was no official timeframe for release (official release came unannounced on 20th September). Before that binary is officially available (in the Store and on the Developer downloads page as a release), it hasn't passed whatever quality control Apple has decided upon. 

> I do get your concern and 100% appreciate it. The only reason I insisted is because I didn't want to be doing this again 2 weeks later.

I expect that the only thing that would have needed changing was the Xcode version number 🙂. 

> I realized the travis build has been building with every merge/commit to the main branch. At the same time it hasnt passed for quite a long time and may still have internal flags making it think its still trying to deploy a new release.

Which build are you referring to? The ones I'm looking at run nightly, against master. The release / deployment task seemed to break with your merge; at the same time the Cocoapods build got fixed with your merge. And by the looks of it, updating that Vendor/xcodetoolchain submodule to your latest changes should fix the current error on the release / deployment task 🙂🤞🏼.

> Because it's a release build it will ONLY pull and build code on the master branch. This includes configuration files, Gemfile, submodules, etc..
> This is one of the main reasons it's such a pain to try and fix. If you have to fix the build itself the changes have to already be on the main branch before you even know if it will work.

This isn't entirely true. Every commit in a PR triggers a build like this (this is from a currently open PR): https://travis-ci.org/parse-community/Parse-SDK-iOS-OSX/builds/587098789

Again, there's a 'deployment' task, which executes `bundle exec rake package:release`, and a Cocoapods task. These are the same tasks that runs on a 'real' release. And you can (and really should) run these locally before pushing things which affect the release process.

> Travis has its own internal build environments that determine everything from what version of ruby and bundler are installed by default to even what version of OSX is running and what simulators are available.

It would be quite unfortunate, and counterproductive, if we didn't get to define the environment our product builds in. Surely Travis obeys our .ruby-version and Gemfile?

> This is what makes it pretty much impossible to test locally. 

It *should* be possible to run these tasks locally. Before your merge I could reproduce the CI results of these tasks on my machine. I can't right now, but I don't think that has anything to do with your changes (it looks like tvOS FacebookUtils is linking against v4 of the FB API, when 1.17.3 moved everything to v5 🤷🏽‍♂️).

> During this process I ran into build errors that dealt with bundler. The bundler issue led to issues with which version of ruby being used. After that I had issues with which simulators and iOS versions where installed. You have to remember. This isnt just a matter of running a simple script for cocoapod execute a build for your podspec. Everything has to line up or you get "build" errors. This is also why I found different environment issues on both Circle and Travis.

Dependency mismatches can be really nasty, and this looked like a painful problem to deal with. I see it as a problem that the 2 environments were doing things differently. Did you find 2 different sources of 'truth' that each environment relies on, or how did you fix this?

**Comment by noobs2ninjas** [comment]
I should be able to run locally too now. Just took a while to get to this point. I had two things that made this take much longer than it probably should have. First travis had lots of mistakes in their documentation pretty much all around. For instance what versions of ruby where needed for which environments. Heck they didn't even document the correct version of macOS is used when specifying a xcode11 environment. The second big issue was that took forever was upgrading jazzy for docs. I spent a few hours trying to figure out what I did that could have messed it up. Turned out it was jazzy's issue and I had to wait for them to release a fix for it.

**Comment by noobs2ninjas** [comment]
I also had another question for you. It seems to me that CircleCI could actually do all this on its own and most of that code is actually already on the config.yml. So why use Travis? Seems like just another thing to update. While Circle had some of the same issues as Travis a good bulk of this was actually specific to Travis.

**Comment by noobs2ninjas** [comment]
Sigh. What a pain in the butt. Even testing xctoolchain changes locally isn't guaranteed. Locally running iOS 13 on iPhone XS worked fine. Travis however changed their systems to only offer OS's on the most recent models. This has changed since last week. I did the same for watchOS, and tvOS. Hopefully this build configuration will last us for quite a while.

**Comment by drdaz** [comment]
> I also had another question for you. It seems to me that CircleCI could actually do all this on its own and most of that code is actually already on the config.yml. So why use Travis? Seems like just another thing to update. While Circle had some of the same issues as Travis a good bulk of this was actually specific to Travis.

I have no idea 😃 This is the first project where I've used CircleCI and Travis. I did wonder the same thing. I imagine there's some functional reason for the setup, some detail that one does and the other doesn't; the previous maintainers seemed pretty solid. But what their reasoning was, I don't know.

> Sigh. What a pain in the butt. Even testing xctoolchain changes locally isn't guaranteed. Locally running iOS 13 on iPhone XS worked fine. Travis however changed their systems to only offer OS's on the most recent models. This has changed since last week. I did the same for watchOS, and tvOS. Hopefully this build configuration will last us for quite a while.
> 
> Oh and of course they have no documentation showing a current list of their available simulators.

This sounds very weird - what if a project wants to test that their UI works on an older / smaller iPhone?

I know that testing this project locally, since we were testing against 12.2 in CI, I needed to manually install the (x)OS 12.2 simulators in Xcode because it was no longer current, and no longer installed with Xcode by default. Maybe this relates to the Xcode version we're testing against in Travis? 

On second thought, probably not... I just updated to Xcode 11 (and my projects broke, yay!), and can see it offers Simulators for a long list of devices. 🤷🏽‍♂️

It would be nice to know how that works, but assuming this config does the job when it hits the build server, we should, as you say, be good for quite a while.

**Comment by noobs2ninjas** [comment]
> This sounds very weird - what if a project wants to test that their UI works on an older / smaller iPhone?

Hey. Thats right! Theres no way they are that dumb.

Ok! I see what they did. Unlike older OS versions they simply removed running iOS 13 on simulators with duplicate screen sizes. So since the iPhone 11, 11 Pro, 11 Pro Max is out now, they removed being able to run iOS 13 on the XS, XS Max, and XR. They also have iOS 13 available on the iPhone 8 and 8 Plus but not on the 7 and 7 Plus.  

What I don't get is why this isn't consistent with other OS. You can run 12.2 down to iOS 10.3.1 on pretty much every phone they offer unless that version shipped with a higher version. So you can run iOS 12.2 on both the 7 and 7 Plus and 8 and 8 Plus as well as the X, XS, XR, XS Plus.

 You'd think it would be the other way around since developers have already had almost a year or more on the older versions. So if anything developers would want to test iOS 13 on as many simulators as possible.

Assuming the same is true across the board I went ahead and did this for tvOS and watchOS. Latest models with latest OS. Everything built across the board when i ran `bundle exec rake package:release` with those changes.

**Comment by noobs2ninjas** [comment]
Actually. You are right to a extent. Just noticed this means you cant test on 4in screens even though iOS 13 is compatible with the iPhone SE as well as 7th gen iPod Touch.

**Comment by noobs2ninjas** [comment]
I think we are good to go here. Finally!

**Comment by TomWFox** [comment]
> Speaking of docs. I really really would like to make a docs for updating this in a future in the event for some reason I'm not available. Question is whats the best place to do this?

Probably best in a wiki page.

**Comment by benpackard** [comment]
Apologies if this is old news but just to mention how simulators can be created with a choice of device x iOS version:

> Xcode no longer creates every available iOS simulator device by default. Instead a set of the most commonly used devices are created. To create other devices — or multiple instances of a device — open the Devices window, select Simulators, click the + button, enter a name, and select the relevant device type and OS version. In Terminal, execute the xcrun simctl create <name> <device type> <OS version> command, for example xcrun simctl create "My iPhone 7" "iPhone 7" iOS13.0. (49428617)

https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes

**Comment by drdaz** [comment]
Nice. That explains the behaviour we've been seeing, and how to control it 👍🏼

I had no idea.

**Comment by noobs2ninjas** [comment]
Well the behavior we've been seeing was because they changed the default simulators included in the environment image they use for each job. I'd imagine the reason it changed this time was because of the release of the iPhone 11. However, if they do continue to make sporadic changes This would be a nice short little script to add to the build.
