### ISSUE TITLE
No completion called after a failed logout

### ISSUE THREAD

**Issue by SebC99** [parse-community/Parse-SDK-iOS-OSX#1462]
We have a "deletion" feature in our app to let users ask for an account deletion.
It uses a cloud-code on the server for the data deletion, which is triggered by the authenticated user (for security reason), then when the server returns, we try to log out the current user, to remove any local data associated with it.
(see https://github.com/parse-community/parse-server/issues/6137#issuecomment-544487343)

Unfortunately, as the user doesn't exists on the server, the logout fails (it succeeds to delete the local data but fails to logout from the server), which wouldn't be an issue in theory.... except that we don't receive the error as the callback of the logout method is never called.

Apparently, when the `[BFTask taskForCompletionOfAllTasks:@[ userLogoutTask, logoutTask ]]` fails because the `userLogoutTask` fails, the task completion is not called at all.

Any idea why it fails?

**Comment by mtrezza** [comment]
What's your Parse SDK and server version to begin with?

I just tested it and the callback works.

**Comment by drdaz** [comment]
@SebC99 Couldn't you make the calls the other way round? Log out the user and then make a Cloud Code call to delete the user?

**Comment by SebC99** [comment]
Last version on both
The callback works for a standard logout but not when it fails after a complete user deletion (user, sessions, installations)

**Comment by mrmarcsmith** [comment]
If the cloud function deletes the user object and the corresponding session tokens and installations. What is the purpose of logging out of the user? Is it so the client doesn’t receive “Invalid session token” error on subsequent calls?

**Comment by SebC99** [comment]
To remove the persistent current user storage (parse internal), and allow a proper detection of a new user after that

**Comment by mtrezza** [comment]
@SebC99 I am not able to reproduce the issue you describe.

You can add the Parse SDK as a sub project to Xcode and set a breakpoint at the logout function to investigate. Without further details I’d assume it is not a bug in the Parse SDK.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SebC99** [comment]
Weird... it fails each time for us. And we did try with breakpoint: the userLogoutTask fails but the BFtask does not... it keeps waiting.

**Comment by noobs2ninjas** [comment]
@SebC99 we are currently forking Bolts as its no longer being maintained any longer and we cant get them to even merge our pull requests to keep it up to date with new versions of Xcode and iOS. Just this morning I sent a few emails trying to see if they wouldnt mind just letting us have it since Bolts was literally created for Parse. 

In either case though I'd definitely consider a different approach IMO. Not only am I almost certain that logging in with a different user overwrite all information that might be maintained by the previous user. I would actually use revokable sessions, delete the user, then wait for the session invalid callback to verify the user is deleted and then clear cache on the entire user class just to be sure. 

Either way. I'll take a look once we can get our Xcode 11 iOS13 release out with our own updated version of bolts incorporated.
