### ISSUE TITLE
Query on PFRelation with Limit < 5 Returns Incorrect Objects

### ISSUE THREAD

**Issue by HackShitUp** [parse-community/Parse-SDK-iOS-OSX#1476]
I've been using Parse since around 2015 and have migrated to AWS ever since. I've become pretty familiar with it but this new issue I found is a bit odd. When you execute a PFQuery on a PFRelation object with a ```limit``` value of **< 5** the query returns incorrect objects. I haven't manipulated the server code, so I'm assuming this is an issue with the iOS SDK(?). Here's an example of what I have:

```
// MARK: - DispatchGroup
let dispatchGroup = DispatchGroup()
        
/// Initialized array of Post objects to append to this class' ```posts``` array each time the user scrolls to the end of the collection view. Useful to sort each new list of Post objects from newest to oldest
var additionalPosts: [Post] = [Post]()
additionalPosts.removeAll()

// Loop through the "Group" PFObjects
for group in groups {
    // MARK: - DispatchGroup
    dispatchGroup.enter()
            
    // MARK: - PFQuery
    let postsQuery = group.relation(forKey: "posts").query()
    postsQuery.order(byDescending: "createdAt")
    postsQuery.skip = 0
    postsQuery.limit = 2    // If 2 it returns the incorrect objects — sometimes not at all. If 5, it works fine.
    postsQuery.findObjectsInBackground { (objects: [PFObject]?, error: Error?) in
        if error == nil {
            // Iterate through each "Post" PFObject
            objects?.forEach({ (object: PFObject) in
                // MARK: - Post
                let post = Post(object, group)
                additionalPosts.append(post)
                            
                // Sort the ```additionalPosts``` array with the new element
                additionalPosts = additionalPosts.sorted(by: {$0.object?.createdAt ?? Date() > $1.object?.createdAt ?? Date()})
            })
                    
            // MARK: - DispatchGroup
            dispatchGroup.leave()
                    
            } else {
                print("\(#file)/\(#line) - Error: \(error?.localizedDescription as Any)")
                // MARK: - DispatchGroup
                dispatchGroup.leave()
            }
        }
    }
```

Essentially, this piece of code gets the first 2 posts per each group the current user is a member of. The reason why we even need to use ```skip``` and ```limit``` on these queries is because we page the ```UICollectionView``` once the user scrolls to the end of the list (classic implementation seen in every product). Once scrolled to the end of the list, the request gets the "next 2 most recent posts per each group you're a part of," but this doesn't happen. It only happens when the limit is > 5.

**Comment by drdaz** [comment]
There’s a few things here.

You say this is a new issue, but what brought it about? Was it an upgrade of the iOS SDK? Can you confirm this code works as you expect in an older version of the SDK?

Also, you’re calling the findObjectsInBackground method in a loop. It’s possible that this won’t do what you’re expecting; the completion block will fire but the loop will carry on and *not* wait for the completion block to finish. It looks like you might be accounting for this using DispatchGroup, effectively making the async call synchronous here. 

Have you tried using a synchronous ‘findObjects’ method in the loop instead of the async method + DispatchGroup approach you’re using? It’s not something you should do in production code, so just for testing. 

If that helps, you should probably look into BFTask(forCompletionOfAllTasksWithResults). This allows you to loop and create asynchronous tasks to be executed (findObjectsInBackground returns a BFTask), and act when all the tasks are complete.

It’s also not obvious how / when your collection view looks at the data generated by your code. This could be a source of timing related issues.

I’ve focused on your code, since I can’t see the data you’re working with to reproduce.

**Comment by drdaz** [comment]
Also, you say this only relates to PFQuery objects from PFRelations. Have you seen this logic work correctly using a 'normal' PFQuery (one not related to a PFRelation)?

**Comment by HackShitUp** [comment]
@drdaz I actually had this issue before when using Parse, I just never made an issue. I'll definitely look into BFTask for something like this. Also, it's quite interesting because this issue is also replicable if you use the ```getFirstObjectInBackground``` method. Given that that method returns the first object, it actually doesn't return the "correct" first object when setting specific key values such as ```.orderBy(descending: "createdAt")```.

I also tried the synchronous ```findObjects``` and it made no difference, the issue persists.

**Comment by drdaz** [comment]
Alright, that definitely suggests an issue on Parse's end. Can you write a test showing the issue? 

I'm thinking an XCTest test that creates the objects with the relation, and then the query returning the unexpected results.

**Comment by HackShitUp** [comment]
@drdaz yea, I'll definitely try and get something built before the end of this month. I can't do this for my server because it's in production and people are using our app. I'll spin something up on AWS and let you know!
