### ISSUE TITLE
[PFUser currentUser] does not update in Watch Extension when log out and vice versa

### ISSUE THREAD

**Issue by PatrickAdams** [parse-community/Parse-SDK-iOS-OSX#148]
I'm having an issue where the Apple Watch is not reflecting the currentUser when changes are made in the iPhone app. Groups and keychains are set up correctly. Noticed some other people having this same issue. When I log out on the iPhone, currentUser is not nil on the watch. When the user is nil on the watch and I log in on the phone, currentUser is still nil.

**Comment by richardjrossiii** [comment]
Thanks for the report. Any chance you can create a small project demonstrating the bug here on github? It really does help us track these things down easier.

**Comment by PatrickAdams** [comment]
Am I wrong in assuming this is the way it should work? With the [PFUser currentUser] always in sync?

-- 
Patrick L. Adams

On September 1, 2015 at 4:47:30 PM, Richard Ross (notifications@github.com) wrote:

Thanks for the report. Any chance you can create a small project demonstrating the bug here on github? It really does help us track these things down easier.

**Comment by nlutsenko** [comment]
Hey @PatrickAdams, your assumption is absolutely correct, there could be a few gotchas about this one, but I think there is a bug here somewhere, for sure.
That's why we have it marked as `needs investigation` in addition to simply `needs more info`.
The repro project would help us tremendously in tracking down the issue you are facing.

**Comment by PatrickAdams** [comment]
Yea, it would take me a decent amount of time to set up a repro project that I don't have at the time. Maybe you could take a look at my existing project?

**Comment by PatrickAdams** [comment]
Ok, so I created a project that reproduces the bug, where should I send it?

**Comment by PatrickAdams** [comment]
@richardjrossiii @nlutsenko Ok, so I created a project that reproduces the bug, where should I send it?

**Comment by nlutsenko** [comment]
You can send it to nlutsenko@fb.com.
Will take a look as fast as I can, and get back to you.

**Comment by PatrickAdams** [comment]
sent.

**Comment by PatrickAdams** [comment]
@richardjrossiii @nlutsenko Hey guys, have you dug into my bug repro project? Curious if you are getting anywhere with this. The launch of my app is dependent on it.

**Comment by amg1976** [comment]
I'm having a similar issue, although I was never able to see the logged user on the app extension

https://github.com/amg1976/Futebol365-iOS

**Comment by kentoh** [comment]
Any updates? We've struggled with this for quite some time. Original bug report (with sample project) that we've filed before issue tracking was moved to Github, if it helps: 

https://developers.facebook.com/bugs/404027086449063/

**Comment by jf367** [comment]
Any updates on this one? It seems to still happen and it's been more than a year now since the original bug report. Thanks!

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.

**Comment by benpackard** [comment]
@TomWFox @mtrezza What would it take to get this one reopened? I believe the issue remains. I am happy to create a demo project on the latest SDKs, but need to be able to log in/out to demonstrate the issue. I don't think I can set up a new Parse Server for this.

I spent a few hours researching similar issues and stepping through the iOS SDK but I couldn't get to the bottom of it. In short, once you set up Keychain sharing and App groups correctly, the extension can access the logged in user, but if the user changes in the main app the extension still has access to the previous state. (Fetches fail, correct, since the token isn't valid.)

**Comment by benpackard** [comment]
@mtrezza Thanks, will do.

**Comment by benpackard** [comment]
@mtrezza I created a new issue with a test project at https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1648 - please let me know over there if I missed anything. Thanks.
