### ISSUE TITLE
createdAt and updatedAt properties are not accessible inside saveInBackground call back

### ISSUE THREAD

**Issue by hatimmakki** [parse-community/Parse-SDK-iOS-OSX#1507]
Hi there,
I am creating a new object and for some reason I need to get the the full saved object including the createdAt and updatedAt properties.

in this code, I am saving the new object.

```swift
        let msg = PFObject(className: "ChatMessage")
        msg["User"] = user
        msg["Message"] = message
        msg["Topic"] = topic
        //messageList.append(message)
        msg.saveInBackground { (success, error) in
            if error == nil {
                //msg.createdAt is nil
            }
        }
```

When I try to access msg .createdAt I always get nil. However, msg.objectId returns the new object id, which is fine.

in order to access the createdAt property, I need to do like this:
```swift
let createdAt = msg.value(forKey: "createdAt") as! NSDate
```
SO, the issue here is that we cannot access createdAt and updatedAT directly.

- I am using Parse 1.17.2
- for more details please see [this](https://stackoverflow.com/questions/61592547/how-to-get-createdat-property-when-saving-a-new-object-using-parse-sdk/61637741?noredirect=1#comment109035440_61637741)

**Comment by noobs2ninjas** [comment]
Try using Parse 1.18.0. I have a feeling that this will render the same result. The primary reason being that those are values set by the server. So, I think this was not updated intentionally in order to keep the save request quick and allow the developer to decide if updating the object is necessary with ``.fetchInBackground()``, ``fetchIfNeededInBackground``, or ``fetchIfNeededInBackgroundWithBlock``
