### ISSUE TITLE
Carthage Xcode >=12 compatibility

### ISSUE THREAD

**Issue by jesusmateos1234** [parse-community/Parse-SDK-iOS-OSX#1591]
Generate xcframework for the next version in order to avoid using carthage workaround

https://github.com/Carthage/Carthage#building-platform-independent-xcframeworks-xcode-12-and-above

@cbaker6

**Comment by cbaker6** [comment]
Thanks for the link, @drdaz is looking at this in #1561

**Comment by mtrezza** [comment]
We may be moving straight to [SPM support](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1453) and skip fixing the carthage build altogether, see discussion in https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1615. In the meantime, I found a rather complex way to build with carthage on Xcode 13.2.1:

1. Use [carthage build script](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md) `carthage.sh` for Xcode >12 compatibility
2. Build all xcframeworks; do not use `--no-use-binaries` as `facebook-ios-sdk` is required as dependency of Parse SDK but [cannot be built from source](https://github.com/facebook/facebook-ios-sdk/blob/main/CHANGELOG.md#1110) in Xcode 13; run: `./carthage.sh update --use-xcframeworks --platform iOS`
3. Add built xcframeworks to Xcode project, except `Parse.xcframework`
4. Open `Carthage/Checkouts/facebook-ios-sdk/samples/SmoketestSPM/SmoketestSPM.xcodeproj` and wait for SMP to download the dependency; see [here](https://github.com/facebook/facebook-ios-sdk/issues/1251#issuecomment-610208586).
5. Build Parse SDK frameworks because `ParseFacebookUtilsV4.xcframework` requires `Parse.framework` (not as xcframework), so it needs to be built and added via `carthage copy-frameworks` in the Xcode project's build phases; run: `./carthage.sh update Parse-SDK-iOS-OSX --platform iOS`

**Comment by mtrezza** [comment]
I'm keeping this issue open as a thread to look for help when building with carthage, but with a note that we intend to focus on Swift Package Manager support (https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1453) instead of fixing carthage build process.

**Comment by mtrezza** [comment]
Closing as release [2.0.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.0.0) supports import via Swift Package Manager.
