### ISSUE TITLE
Error in macOS project _OBJC_CLASS_$_PFProductsRequestHandler version 2.0.2

### ISSUE THREAD

**Issue by extnous** [parse-community/Parse-SDK-iOS-OSX#1699]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description

Getting the following compilation errors

> Undefined symbol: _OBJC_CLASS_$_PFProductsRequestHandler

Parse-SDK-iOS-OSX added with SPM.
Errors only app for mac os application. Project for iOS App no compilation errors.

### Steps to reproduce
Compile a new mac os project that make use of Parse-SDK-iOS-OSX version 2.0.1 or 2.0.2.

### Actual Outcome
<img width="631" alt="Снимок экрана 2023-02-08 в 16 37 24" src="https://user-images.githubusercontent.com/5279382/217532798-6499f642-6181-4131-9fcf-80a80e643667.png">

### Expected Outcome
No compilation errors.

###  Environment
ObjC SDK version: `2.0.2`
Mac OS - Ventura 13.0
Apple M1 Pro
Xcode - Version 14.2 (14C18)

Client
- Parse ObjC SDK version: `2.0.2`

Server
- Parse Server version: `N/A`
- Operating system: `N/A`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `N/A`

Database
- System (MongoDB or Postgres): `N/A`
- Database version: `N/A`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `N/A`

**Comment by rogernolan** [comment]
@extnous did you find a workaround for the linker error?

**Comment by rogernolan** [comment]
If you just want to get your project linking and surprise this link error, you can add a stub class to the project with the same name:

PFProductsRecord.h

```
#import <Foundation/Foundation.h>
@interface PFProductsRecord : NSObject
@end
```

and 

PFProductsRequestHandler.m

```
#import "PFProductsRequestHandler.h"
@implementation PFProductsRequestHandler
@end
```

**Comment by santiagoprieto** [comment]
I have the same issue. It might be because `PFProduct` and `PFPurchase` are unavailable for Mac as marked by the `PF_OSX_UNAVAILABLE_WARNING`. 

Is there an easy way to ensure these unavailable files are not included in the Mac builds? I didn't have this issue when using CocoaPods, but now that we moved to SPM this occured.

**Comment by sidan5** [comment]
Same issue here running MacBook Pro M2.

**Comment by santiagoprieto** [comment]
This issue is still affecting my app. The interim fix suggested by @rogernolan has not worked for me. If I knew how to fix it in the parse code I would. Help! Anyone?

**Comment by santiagoprieto** [comment]
This is so frustrating.

**Comment by santiagoprieto** [comment]
Because of this error the whole Parse-SDK-iOS-OSX should drop the "OSX" from its name. It won't compile since February for Mac apps.

**Comment by dplewis** [comment]
@santiagoprieto I don't know why PFProduct isn't supported on Mac, probably because StoreKit didn't support Mac at the time of this SDK creation. Looks like it does now from MacOS 10.7+ and StoreKit 2 has been release.

If you want to look into this you can add `PF_TARGET_OS_OSX` in places required like [here](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/4c130ee61302f22f46436cc477960fa48d957bd9/Parse/Parse/Source/PFProduct.m#L11)

You can use the Starter Projects included in this SDK for easier development.

https://github.com/parse-community/Parse-SDK-iOS-OSX/tree/master/ParseStarterProject/OSX

I've created a PR to fix this issue https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1739

**Comment by santiagoprieto** [comment]
@dplewis and @mtrezza you are the best. Thanks for your rad improvement. My app is now compiling perfectly and I'm ready to push a long-awaited update to my users.
