### ISSUE TITLE
Can no longer use PFGeoPoint for fetching locations while app is backgrounded 

### ISSUE THREAD

**Issue by adammlevy** [parse-community/Parse-SDK-iOS-OSX#506]
iOS 9 now requires apps which are fetching location in the background to enable allowsBackgroundLocationUpdates however this API is not exposed in the Parse API. What is the correct way to perform location updates while the app is backgrounded with the Parse API?

**Comment by richardjrossiii** [comment]
Essentially, as long as you set `NSLocationAlwaysUsageDescription` instead of `NSLocationWhenInUseUsageDescription`, we should allow tracking background location updates without requiring any code changes.

We probably should document this better...

See [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/Internal/PFLocationManager.m#L117-L125) for the code that implements location updating.

**Comment by adammlevy** [comment]
This code only shows setting the authorization status.  Apps built with iOS 9 must set allowsBackgroundLocationUpdates to YES every time the location manager will be used for fetching a location while the app is backgrounded. Am I missing something or is allowsBackgroundLocationUpdates  actually being set?   [Doc](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instp/CLLocationManager/allowsBackgroundLocationUpdates)

**Comment by nlutsenko** [comment]
@adammlevy, looks like you are right, we don't expose the ability to set this property on a CLLocationManager that we are using.
Since we don't expose any other location manager APIs other than simply getting a geo point for current location - I would suggest using your own custom CLLocationManager to have that precise control, then you can always construct a PFGeoPoint from a CLLocation by using `geoPointWithLocation:`

**Comment by adammlevy** [comment]
Sounds good. Thanks for the response.
