### ISSUE TITLE
Misleading `-[NSArray containsObject:]` in relationship array

### ISSUE THREAD

**Issue by natanrolnik** [parse-community/Parse-SDK-iOS-OSX#567]
Hey iOS Parsers. I had a problem a few days ago, and I'll try to explain it (I'm not sure it's an SDK issue, or I'm doing something wrong). Imagine the following scenario:
- I have a local instance of a `Organization` (a `NSManagedObject` subclass)
- The `PFOrganization` object has an array of `PFInstallations`, to keep track of which of them 

Every time the app is launched, I fetch the current user, to see if there were any changes, so I can update it locally:

``` objc
//fetch the organization object... in completion block, do:

if ([parseOrg.updatedAt laterDate:localOrg.updatedAt] == parseOrg.updatedAt) {
   //call function to update the organization locally
    [localOrg updateFromParseOrganization:parseOrg];
}

//now, check if the organization already have the current installation added to the `installations` property
PFInstallation *currentInstallation = [PFInstallation currentInstallation];
if (![parseOrg[@"installations"] containsObject:currentInstallation]) {
    [parseOrg addUniqueObject:currentInstallation forKey:@"installations"];
    [parseOrg saveInBackground];
}
```

What happens is, that every time the `containsObject` is called, it will result in false - because the currentInstallation is **not and will never be** the exact same object in memory. This way, it will always try to add the unique object, saving it, saving/updating the parse object. The next time the fetch will happen, the `laterDate:` comparison will also enter the if, because the `parseOrg` has been updated/saved from the last time, and we have an endless "loop", because the `localOrg` will never be up to date with the server (although it is, in fact).

It may be a bit confusing, but the final point is:

1 - Do the `containsObject:` should return `YES` in this check? It won't. I ended up doing a `for` loop to check each `objectId` to see if it really contains the installation.
1a - If it should return `YES` is this a bug somehow? Should Parse override the implementation of `containsObject`?
1b - If not, because that's how `NSArray`s work (comparing the memory but not the uniqueness of the installation), should I be using a `PFRelation` in this situation?

2 - In other words, what's the difference between storing other objects as `NSArray` or as `PFRelation`?

Hope it's clear enough, if not, I'm here to explain :smile:

**Comment by richardjrossiii** [comment]
ParseObject does not implement `-equals:` or `hash`, which means that you cannot use `-containsObject:` `-indexOfObject:`, or any of its friends.

One solution would be to use LocalDataStore, which makes a process-wide guarantee that there can only be one pointer to a given PFObject with a particular objectId/className pair.

That means that you then will have your current installation again being the exact same object in memory, and you should be able to use `containsObject:` again.

`PFRelations` are essentially the equivalent of a tradition RDBMS's 'join table'. Useful if you need to specifically query for a specific object inside that relation, otherwise, not super helpful. It won't help you in this case, as there is no equivalent to `-containsObject:` in the public API.
