### ISSUE TITLE
Allow accessing PFReachability

### ISSUE THREAD

**Issue by natanrolnik** [parse-community/Parse-SDK-iOS-OSX#622]
Dear Parsers!

I'm trying to declare `#import "PFReachability.h` so I can show some information to the users. I already use a reachability manager from myself, but I want to get rid of it - It's based on the `AFNetworking` one, but it has a few bugs from my tests.

Is the PFReachability class supposed to not be touched by developers? Why :smiley: ?

**Comment by nlutsenko** [comment]
Hey @natanrolnik, the reason is quite simple:
It's a private class that we use internally to power few things in the SDK (you can find them with search), and exposing the class in it's current state would lead to potentially breaking behavior, if you say remove all listeners, as well as we want to limit the public API surface for compatibility/maintainability reasons.

I can see it being super useful though for anyone in the general public, and taking into account that we can use clang module maps to expose a custom private import - we probably can make it happen.

@grantland @richardjrossiii @stanleyw 
What do you guys think about this idea? Does it make sense to expose PFReachability under say
`@import Parse.Private.PFReachability;` and let people actually use it?
It won't add it to public headers and won't let usage of `@import Parse.PFReachability;`

**Comment by natanrolnik** [comment]
When I saw the `removeAllListeners` method, I imagined the potential problems/risks. But for sure a safer way can be found, as you mentioned!

**Comment by codywinton** [comment]
What is the status on this?

**Comment by nlutsenko** [comment]
@grantland @richardjrossiii 
Are we ok adding "Private" headers to the framework?
That is the only way that comes to my mind that we could allow this being used without having to commit to maintenance of API on that class.

**Comment by richardjrossiii** [comment]
@nlutsenko Not a huge fan of this idea, even if we don't have 'official' support for the headers, inevitably there will end up being a complaint that we break backwards compatibility the second we make these APIs even semi-public. 

I highly recommend maintaining a fork if you really need this to be public, while merging changes back from our master every major release.

Just my 2¢.
