### ISSUE TITLE
ParseFacebookUtils for OS X

### ISSUE THREAD

**Issue by SergeyK-Wind** [parse-community/Parse-SDK-iOS-OSX#691]
We have iOS application. It uses authorization through Facebook to synchronize data. Now we develop OSX-version. But there is no "parse+facebook" sdk for OSX.

Please advise what can we do? Thanks.

**Comment by nlutsenko** [comment]
Hey @SergeyK-Wind, the primary reason for no ParseFacebookUtils on OS X is actually absence of official Facebook SDK for OS X.

I am going to mark this as enhancement so we are tracking this (and rename the title of the issue slightly).

P.S. I have few ideas on how to implement this even without official FBSDK, using both Accounts.framework as well as Web Browser Auth. Let me see if it's easy to grab fruit.

**Comment by SergeyK-Wind** [comment]
@nlutsenko Thank you for the reply. Indeed, this issue is very important for us. We would also like to ensure security of users' account data.

**Comment by SergeyK-Wind** [comment]
@nlutsenko Hello again! I am wondering if there is any news regarding my issue?

**Comment by nlutsenko** [comment]
@SergeyK-Wind, I would recommend starting building this on your own and I'll gladly contribute to it.

**Comment by SergeyK-Wind** [comment]
@nlutsenko Actually we found a solution which provides a Facebook authorization in OS X app:

https://github.com/philippec/PhFacebook
https://github.com/cobook/facebook-osx-sdk

However, we are not entirely satisfied with this option since we have to generate a user’s password ourselves basing on a Facebook identifier what leads to weak security of their account. A malefactor can generate a user’s password and therefore get an access to their account. 

I am afraid we will have to give up on using Facebook if we don’t find a more secure authentication method.

**Comment by nlutsenko** [comment]
Yeah, that sounds pretty bad. Turns out that we have a public API on `PFUser` - `registerAuthenticationDelegate:forAuthenticationType:` that is public and is the one being used by our utils.

If you look at the source of [ParseFacebookUtils](https://github.com/ParsePlatform/ParseFacebookUtils-iOS) - you'll see that all it takes for our FB Auth is committing to a specific format that is being sent to the server. Things like `fbid`, `authToken`, `expirationDate` for the token.
You can plug-in your own FacebookAuthenticationProvider on OS X and simply provide this info in the same format, which will get you a safe and nice authentication on OS X.

You can get auth token by using Accounts.framework or by using any of the frameworks that you referenced above, and as a result fbid/expirationDate by simply getting the token information from Graph API.

**Comment by SergeyK-Wind** [comment]
Good day @nlutsenko. Currently we are trying to use Parse JavaScript SDK and WKWebView. We have achieved successful authorisation through Facebook by several ways:

1) Using auth_data + method `[PFUser logInWithAuthTypeInBackground: authData:]` + authentication delegate
2) Using accessToken + method `[PFUser becomeInBackground: block:]`
3) More complex way: generate random login and password, link them with Facebook-Parse-account and make authorisation through `[PFUser logInWithUsernameInBackground:password:block]`

First and second ways seems simplier, but we need some clarifications:
- Which one is preferable? and why?
- If we will use native Parse+Facebook SDK, Facebook-auth token expires in 60 days (without any actions in application). In our case will expiration date prolongates automatically? or we need to make some additional API calls?
