### ISSUE TITLE
Certificate Pinning

### ISSUE THREAD

**Issue by kingmatusevich** [parse-community/Parse-SDK-iOS-OSX#799]
The SDKs should be compatible with pinned certificates for connecting to the Parse Servers, allowing for faster, safer deployment, particularly in small or internal deployments.

**Comment by nlutsenko** [comment]
I agree with pinned certificates, though requiring this for everyone would probably be less than ideal, taking into account that this would explicitly require people to update their apps when a certificate expires/changes.

I would recommend changing the source code in place to allow this, since the change is relatively small and would also allow you to bundle any certificate you want if you are using self-hosted Parse Server.

**Comment by kingmatusevich** [comment]
I'm not suggesting it as the only alternative, but I'm saying it should be one to allow the use of self signed roots.

**Comment by nlutsenko** [comment]
Aha, got you.
I think the ideal API would then be as an additional property on the `ParseClientConfiguration` class to allow for trust policy configuration.

**Comment by adonoho** [comment]
So as to not duplicate work, is the team at Parse working on adding certificate pinning? Or is this something we should be doing to the Parse SDK as an open source project?

**Comment by markuswinkler** [comment]
Any progress on this?

**Comment by acudworth** [comment]
Would be great to see this implemented asap, all too easy for a malicious user to intercept app <-> server communication at the moment

**Comment by markuswinkler** [comment]
*ping*

**Comment by sunlyear** [comment]
> Aha, got you.
> I think the ideal API would then be as an additional property on the `ParseClientConfiguration` class to allow for trust policy configuration.

Can you explain how to allow this trust policy in the latest SDK?
