### ISSUE TITLE
Cache cloud function results

### ISSUE THREAD

**Issue by AmbroiseCollon** [parse-community/Parse-SDK-iOS-OSX#889]
Is it possible to cache cloud function results ? It would be much appreciated !

**Comment by nlutsenko** [comment]
We don't have a system in place for this, but you could pin the objects returned into local datastore.
Or use `NSCoding`-based encoding to save them to disk yourself.

Marking this as a feature request, since having this functionality is very useful in general.

@AmbroiseCollon, do you see it being useful with Local Datastore together? Or only in use with Query Caching, meaning without Local Datastore?

**Comment by AmbroiseCollon** [comment]
I'm not sure about what's going on under the hood. But I guess it would be really useful to have a query caching like system. So that you don't have to worry about doing it yourself. When I have to make a decision between writing code in app or in cloud code, I sometime chose app whereas I would chose cloud if there were caching.

**Comment by AmbroiseCollon** [comment]
There is repo here : https://github.com/updatezen/PFCloud-Cache It's not maintained anymore but maybe there are interesting things there too.

**Comment by AmbroiseCollon** [comment]
Any update on this ?

**Comment by AmbroiseCollon** [comment]
Just realized I did not answer your question. I see it working without Local Data Store, using query caching in order to have a common experience with query and cloud function.

**Comment by flovilmart** [comment]
I recommend just using a pin for your cloud functions results if possible.

**Comment by AmbroiseCollon** [comment]
That's what I do. The only thing is you can have both cache and local data store working. It's OK for me as I'm moving all my queries to server. But I figured it could be useful.

**Comment by agrt56** [comment]
An app-wide caching mechanism for cloud code functions would be a useful addition. I used baasbox for my last project, until i realised that it's not longer maintained. It had a very good server side scripting engine which supported such a mechanism:

https://github.com/baasbox/baasbox/wiki/Plugin-Engine#cache-since-100-m3

Use-Case: Caching a limited set of non sensitive db entries, that don't change often. You could update the cache after saving new entries and retrieve cached entries on function call. The users get their results directly from the cache. No further db querys required.

This would be useful for e.g. a custom app startup query, where multiple static entries from different db classes are needed.

**Comment by JulienLevallois** [comment]
@AmbroiseCollon did you find a solution ? I would to have this feature too
